apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}-nginx-test
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: nginx
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx-test
  labels:
    app: nginx-test
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: nginx-test
