apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: build-test-file
          image: nobidev/base
          command:
            - bash
            - -c
            - |
              touch /www/index.html
              dd if=/dev/urandom of=/www/test bs={{ .Values.size }} count=1
          volumeMounts:
            - name: www
              mountPath: /www
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
              hostPort: {{ .Values.hostPort }}
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
          livenessProbe:
            httpGet:
              port: http
        - name: self-test
          image: nobidev/base
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - |
                  if [ $(curl -s localhost/test | wc -c) != $(numfmt --from=iec {{ .Values.size }}) ]; then
                    exit 1
                  fi
      volumes:
        - name: www
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app: nginx
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: nginx
