apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}-whoami
  labels:
    app: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-whoami
  labels:
    app: whoami
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: whoami
